config/routes.rb
Todos::Application.routes.draw do
  root "page#home_page", as: :home

  get "login" => "session#login", as: :login
  get "logout" => "session#destroy", as: :logout
  post "authenticate" => "session#authenticate"

  resources :users, only: [ :new, :create ]

  resources :todos, only: [ :index, :create, :update, :destroy ]

  

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :title, :user, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos
  has_secure_password
  validates :email, presence: true
  validates :email, uniqueness: true

  def self.authenticate email, password
    user = User.find_by_email email

    if user
      user.authenticate(password)
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
 
  # Finds the User with the ID stored in the session with the key
  # :current_user_id This is a common way to handle user login in
  # a Rails application; logging in sets the session value and
  # logging out removes it.
  def current_user
    @current_user ||= session[:current_user_id] &&
      User.find_by(id: session[:current_user_id])
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def home_page
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def authenticate
    if user = User.authenticate(params[:email], params[:password])
      # Save the user ID in the session so it can be used in
      # subsequent requests
      puts user.inspect
      session[:current_user_id] = user.id
      current_user
      flash[:success] = "Successfully logged in"
      redirect_to todos_path
    else
      flash[:error] = "Wrong username and password"
      redirect_to login_path
    end
  end

  def login
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    flash[:success] = "Successfully logged out"
    redirect_to home_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_filter :authenticate

  def index
    @todos = @current_user.todos.order("created_at DESC")
    puts "todos"
    puts @todos.count
  end

  def create
    @todo = @current_user.todos.new create_todo_params

    if @todo.save
      render json: @todo, status: :ok
    else
      render json: { errors: @todo.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    @todo = @current_user.todos.find_by_id params[:id]

    if @todo
      if @todo.update(update_todo_params)
        head :ok
      else
        head :unprocessable_entity
      end
    else
      head :not_found
    end
  end

  def destroy
    @todo = @current_user.todos.find_by_id params[:id]
    
    if @todo
      @todo.destroy
      head :ok
    else
      head :not_found
    end
  end

  private
  def authenticate
    if current_user.nil?
      flash[:warning] = "You must be logged in to view the todos page"
      redirect_to login_path
    end
  end

  def create_todo_params
    params.require(:todo).permit(:title, :description)
  end

  def update_todo_params
    params.require(:todo).permit(:title, :description, :completed)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new create_user_params

    if @user.save
      flash[:success] = "Successfully registered"
      redirect_to login_path
    else
      render :new
    end
  end

  private
  def create_user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <span id="logo">Todos</span>
    <ul id="top-nav">
      <% if @current_user %>
        <li><%= link_to "Logout", logout_path %></li>
      <% else %>
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "Register", new_user_path %></li>
        <li><%= link_to "Login", login_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <!-- Optional theme -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/page/home_page.html.erb
<div id="home-page" class="container">
  
  <% if flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end %>

  <h1>What is Todos?</h1>
  <p>Todos is a simple to use application that allows you to manage your time better.</p>
  <p>Simply create an account and get going!</p>
</div>

app/views/session/login.html.erb
<div id="login" class="container">
  <% if flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end %>

  <% if flash[:warning] %>
    <div class="alert alert-warning">
      <%= flash[:warning] %>
    </div>
  <% end %>

  <h1>Login</h1>

  <% if flash[:error] %>
    <ul class="alert alert-danger">
      <li><%= flash[:error] %></li>
    </ul>
  <% end %>

  <%= form_tag '/authenticate' do %>
    <div class="form-group">
      <%= label_tag :email %>
      <%= text_field_tag :email, nil, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= label_tag :password %>
      <%= password_field_tag :password, nil, class: "form-control" %>
    </div>
    <button type="submit" class="btn btn-default">Login</button>
  <% end %>

app/views/todos/create.html.erb
<h1>Todos#create</h1>
<p>Find me in app/views/todos/create.html.erb</p>

app/views/todos/delete.html.erb
<h1>Todos#delete</h1>
<p>Find me in app/views/todos/delete.html.erb</p>

app/views/todos/index.html.erb
<div id="todos-index" class="container">
  
  <% if flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end %>
  
  <h1>Todos</h1> 
  <div id="plus-control">
    <span class="fa fa-plus"></span>
    <span class="filter">Show all</span>
  </div>
  <div class="list-group">
    <% @todos.each do |todo| %> 
      <div class="list-group-item" data-id="<%= todo.id %>">
        <div class="info">
          <% if todo.completed %>
            <span class="check fa fa-check-square-o"></span>
          <% else %>
            <span class="check fa fa-square-o"></span>
          <% end %>
          <h4 class="list-group-item-heading"><%= todo.title %></h4>
          <p class="list-group-item-text"><%= todo.description %></p>
          <span class="edit fa fa-pencil"></span>
          <span class="delete fa fa-trash-o"></span>
        </div>
        <div class="form" style="display: none;">
          <ul class="errors alert alert-danger">
          </ul>
          <div class="form-group">
            <input class="form-control title" placeholder="Title" value="<%= todo.title %>"/>
          </div>
          <div class="form-group">
            <textarea class="form-control description" placeholder="Description"><%= todo.description %></textarea>
          </div>  
          <div class="form-group">
            <button class="submit btn btn-default">Submit</button>
            <button class="cancel btn btn-default">Cancel</button>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="todo-clone list-group-item active">
    <div class="info" style="hidden">
      <span class="check fa fa-square-o"></span>
      <h4 class="list-group-item-heading"></h4>
      <p class="list-group-item-text"></p>
      <span class="edit fa fa-pencil"></span>
      <span class="delete fa fa-trash-o"></span>
    </div>
    <div class="form">
      <ul class="errors alert alert-danger">
      </ul>
      <div class="form-group">
        <input class="form-control title" placeholder="Title" />
      </div>
      <div class="form-group">
        <textarea class="form-control description" placeholder="Description"></textarea>
      </div>  
      <div class="form-group">
        <button class="submit" class="btn btn-default">Submit</button>
        <button class="cancel" class="btn btn-default">Cancel</button>
      </div>
    </div>
  </div>
</div>

app/views/todos/update.html.erb
<h1>Todos#update</h1>
<p>Find me in app/views/todos/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div id="users-new" class="container">
  <h1>Register</h1>

  <% if @user && @user.errors.any? %>
    <ul class="alert alert-danger">
      <% @user.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for @user, html: { class: "container" } do |f| %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  
  <% end %>
</div>